### PR TITLE
Quick Mill Cold Start Kp

### PR DESCRIPTION
**Pull request by cottec**
To fix Cold Start Kp being too low for Quick Mill Machines

### CODE REVIEW

**Comment by kjyv** [comment]
The max value should maybe be a bit larger that the value from the manual - How about 350?

**Comment by cottec** [comment]
feel free, shouldnt harm anything, but not sure if more is needed at all :)

**Comment by kjyv** [comment]
I can't change your pull request ;)

**Comment by cottec** [comment]
ups, changed :)

**Pull request merged**
